Repository bonitasoft/bonita-ui-designer-artifact-builder, pull requests merged in 2023-10, with the labels that each got.

#79 feat(REST error codes handling): Handle 401 and 503 error on Bonita REST requests
  generator-angularjs/gulp/config.js
  generator-angularjs/package.json
  generator-angularjs/src/main/resources/templates/page.hbs.html
  generator-angularjs/src/main/resources/templates/page/assets/css/style.css
  generator-angularjs/src/main/resources/templates/page/assets/json/localization.json
  generator-angularjs/src/main/runtime/js/runtime.module.js
  generator-angularjs/src/main/runtime/js/services/restInterceptorFactory.js
  generator-angularjs/src/test/javascript/karma.conf.js
  generator-angularjs/src/test/javascript/spec/services/restInterceptorFactory.spec.js
  generator-angularjs/src/test/resources/org/bonitasoft/web/angularjs/rendering/fragmentWithNoContext.html
  generator-angularjs/src/test/resources/org/bonitasoft/web/angularjs/rendering/page.html
  generator-angularjs/src/test/resources/org/bonitasoft/web/angularjs/rendering/pageCustomDisplayName.html
  generator-angularjs/src/test/resources/org/bonitasoft/web/angularjs/rendering/pageWithNoContext.html
  generator-angularjs/yarn.lock
Labels: enhancement, review needed

#83 feat(REST error codes handling): add migration step for error dialog css
  artifact-builder/src/main/java/org/bonitasoft/web/designer/UiDesignerCoreFactory.java
  artifact-builder/src/main/java/org/bonitasoft/web/designer/migration/StyleAddErrorDialogPropertiesMigrationStep.java
  artifact-builder/src/test/java/org/bonitasoft/web/designer/migration/StyleAddErrorDialogPropertiesMigrationStepTest.java
  generator-angularjs/src/main/resources/templates/migration/assets/css/styleAddErrorDialogProperties.css
  generator-angularjs/src/main/resources/templates/page/assets/css/style.css
  generator-angularjs/src/main/runtime/js/services/restInterceptorFactory.js
  pom.xml
Labels: enhancement, review needed

#84 feat(HTTP error dialog): add migration step for translations
  artifact-builder/src/main/java/org/bonitasoft/web/designer/UiDesignerCoreFactory.java
  artifact-builder/src/main/java/org/bonitasoft/web/designer/controller/asset/AssetService.java
  artifact-builder/src/main/java/org/bonitasoft/web/designer/migration/LocalizationAddErrorDialogTranslationsMigrationStep.java
  artifact-builder/src/test/java/org/bonitasoft/web/designer/migration/LocalizationAddErrorDialogTranslationsMigrationStepTest.java
  artifact-builder/src/test/resources/org/bonitasoft/web/designer/migration/expectedLocalization.json
  artifact-builder/src/test/resources/org/bonitasoft/web/designer/migration/initialLocalization.json
  generator-angularjs/src/main/resources/templates/migration/assets/json/localizationAddErrorDialogTranslations.json
  model/src/main/java/org/bonitasoft/web/designer/model/JacksonJsonHandler.java
  model/src/main/java/org/bonitasoft/web/designer/model/JsonHandler.java
  model/src/main/java/org/bonitasoft/web/designer/model/LocalizationPrettyPrinter.java
Labels: enhancement

#86 fix(workspace): initialize page index at startup
  artifact-builder/src/main/java/org/bonitasoft/web/designer/workspace/Workspace.java
  artifact-builder/src/test/java/org/bonitasoft/web/designer/workspace/WorkspaceTest.java
Labels: bug

#91 fix(cache): Add model version query param to vendor and runtime js
  artifact-builder/src/main/java/org/bonitasoft/web/designer/ArtifactBuilderFactory.java
  generator-angularjs/src/main/java/org/bonitasoft/web/angularjs/AngularJsGeneratorStrategy.java
  generator-angularjs/src/main/java/org/bonitasoft/web/angularjs/rendering/DefaultHtmlGenerator.java
  generator-angularjs/src/main/resources/templates/page.hbs.html
  generator-angularjs/src/test/java/org/bonitasoft/web/angularjs/rendering/DefaultHtmlGeneratorTest.java
  generator-angularjs/src/test/resources/org/bonitasoft/web/angularjs/rendering/fragmentWithNoContext.html
  generator-angularjs/src/test/resources/org/bonitasoft/web/angularjs/rendering/page.html
  generator-angularjs/src/test/resources/org/bonitasoft/web/angularjs/rendering/pageCustomDisplayName.html
  generator-angularjs/src/test/resources/org/bonitasoft/web/angularjs/rendering/pageWithNoContext.html
Labels: review needed

#96 fix: style error on migration step
  artifact-builder/src/main/java/org/bonitasoft/web/designer/migration/StyleAddErrorDialogPropertiesMigrationStep.java
  artifact-builder/src/main/java/org/bonitasoft/web/designer/migration/StyleAddModalContainerPropertiesMigrationStep.java
  artifact-builder/src/test/java/org/bonitasoft/web/designer/migration/StyleAddErrorDialogPropertiesMigrationStepTest.java
  artifact-builder/src/test/java/org/bonitasoft/web/designer/migration/StyleAddModalContainerPropertiesMigrationStepTest.java
  generator-angularjs/src/main/resources/templates/migration/assets/css/styleAddErrorDialogProperties.css
  generator-angularjs/src/main/resources/templates/migration/assets/css/styleAddModalContainerProperties.css
Labels: bug
