Repository bonitasoft/bonita-ui-designer-artifact-builder, pull requests merged in 2023-08, with the labels that each got.

#22 feat(builder): expose artifacts getStatus
  artifact-builder/src/main/java/org/bonitasoft/web/designer/AngularJsArtifactBuilder.java
  artifact-builder/src/main/java/org/bonitasoft/web/designer/ArtifactBuilder.java
  artifact-builder/src/test/java/org/bonitasoft/web/designer/AngularJsArtifactBuilderTest.java
Labels: enhancement

#23 feat(widgets): Apply migration on provided widgets
  artifact-builder/src/main/resources/widgets/pbAutocomplete/pbAutocomplete.json
  artifact-builder/src/main/resources/widgets/pbButton/pbButton.json
  artifact-builder/src/main/resources/widgets/pbChart/pbChart.json
  artifact-builder/src/main/resources/widgets/pbCheckbox/pbCheckbox.json
  artifact-builder/src/main/resources/widgets/pbChecklist/pbChecklist.json
  artifact-builder/src/main/resources/widgets/pbContainer/pbContainer.json
  artifact-builder/src/main/resources/widgets/pbCurrencyInput/pbCurrencyInput.json
  artifact-builder/src/main/resources/widgets/pbDataTable/pbDataTable.json
  artifact-builder/src/main/resources/widgets/pbDatePicker/pbDatePicker.json
  artifact-builder/src/main/resources/widgets/pbDateTimePicker/pbDateTimePicker.json
  artifact-builder/src/main/resources/widgets/pbFileViewer/pbFileViewer.json
  artifact-builder/src/main/resources/widgets/pbFormContainer/pbFormContainer.json
  artifact-builder/src/main/resources/widgets/pbImage/pbImage.json
  artifact-builder/src/main/resources/widgets/pbInput/pbInput.json
  artifact-builder/src/main/resources/widgets/pbLink/pbLink.json
  artifact-builder/src/main/resources/widgets/pbModalContainer/pbModalContainer.json
  artifact-builder/src/main/resources/widgets/pbRadioButtons/pbRadioButtons.json
  artifact-builder/src/main/resources/widgets/pbRichTextarea/pbRichTextarea.json
  artifact-builder/src/main/resources/widgets/pbSaveButton/pbSaveButton.json
  artifact-builder/src/main/resources/widgets/pbSelect/pbSelect.json
  artifact-builder/src/main/resources/widgets/pbTabContainer/pbTabContainer.json
  artifact-builder/src/main/resources/widgets/pbTable/pbTable.json
  artifact-builder/src/main/resources/widgets/pbTabsContainer/pbTabsContainer.json
  artifact-builder/src/main/resources/widgets/pbText/pbText.json
  artifact-builder/src/main/resources/widgets/pbTextarea/pbTextarea.json
  artifact-builder/src/main/resources/widgets/pbTitle/pbTitle.json
  artifact-builder/src/main/resources/widgets/pbUpload/pbUpload.json
Labels: enhancement

#24 ci: Adapt crowin action since code splitting
  .github/workflows/crowdin-upload.yml
Labels: github_actions

#29 feat: Delete MigrationStatusReport class
  artifact-builder/src/main/java/org/bonitasoft/web/designer/service/AbstractArtifactService.java
  artifact-builder/src/test/java/org/bonitasoft/web/designer/DefaultArtifactBuilderTest.java
  artifact-builder/src/test/java/org/bonitasoft/web/designer/controller/export/properties/FragmentPropertiesBuilderTest.java
  artifact-builder/src/test/java/org/bonitasoft/web/designer/migration/DataExposedMigrationStepTest.java
  artifact-builder/src/test/java/org/bonitasoft/web/designer/service/FragmentServiceTest.java
  artifact-builder/src/test/java/org/bonitasoft/web/designer/service/PageMigrationApplyerTest.java
  artifact-builder/src/test/java/org/bonitasoft/web/designer/service/PageServiceTest.java
  model/src/main/java/org/bonitasoft/web/designer/model/MigrationStatusReport.java
  model/src/test/java/org/bonitasoft/web/designer/builder/FragmentBuilder.java
  model/src/test/java/org/bonitasoft/web/designer/builder/PageBuilder.java
  model/src/test/java/org/bonitasoft/web/designer/model/page/PageTest.java
Labels: enhancement

#41 fix(properties): GeneratorProperties
  artifact-builder/src/main/java/org/bonitasoft/web/designer/ArtifactBuilderFactory.java
  artifact-builder/src/main/java/org/bonitasoft/web/designer/config/UiDesignerPropertiesBuilder.java
  artifact-builder/src/main/java/org/bonitasoft/web/designer/config/WorkspaceUidProperties.java
  artifact-builder/src/test/java/org/bonitasoft/web/designer/i18n/LanguagePackBuilderTest.java
  artifact-builder/src/test/java/org/bonitasoft/web/designer/workspace/WorkspaceInitializerTest.java
  artifact-builder/src/test/java/org/bonitasoft/web/designer/workspace/WorkspaceMigrationTest.java
  artifact-builder/src/test/java/org/bonitasoft/web/designer/workspace/WorkspaceTest.java
  generator-angularjs/src/main/java/org/bonitasoft/web/angularjs/AngularJsGeneratorStrategy.java
  generator-angularjs/src/main/java/org/bonitasoft/web/angularjs/GeneratorProperties.java
Labels: bug
